name: plugin_six2
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.6
  dio: ^5.5.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  provider: ^6.0.3
  flutter_widget_from_html_core: 0.14.12
  xxc_flutter_utils:
    git:
      url: https://github.com/rdchgaa/xxc_flutter_utils.git
      ref: 0bf9a42
  path_provider: ^2.0.2
  url_launcher: ^6.3.0
#  package_info_plus: ^8.0.0
  package_info_plus: 4.1.0
  #  flutter_cache_manager: 3.0.1
  image_picker: 0.8.9

  vibration: ^1.9.0
  permission_handler: ^11.3.1
  fixnum: ^1.0.1
  adobe_xd: ^2.0.1
  flutter_svg: 1.0.3

  audioplayers: 5.2.1
  audio_session: 0.1.17
  extended_image: 6.4.1
  flutter_shaders: 0.1.2
  scratcher: 2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.plugin_six2
        pluginClass: PluginSix2Plugin
      ios:
        pluginClass: PluginSix2Plugin
      web:
        pluginClass: PluginSix2Web
        fileName: plugin_six2_web.dart

  #  uses-material-design: true

  #  assets:
  #    - assets/
  #    - assets/assets_six/languages/
  #    - assets/assets_six/emojis/
  #    - assets/assets_six/images/
  #    - assets/assets_six/html/zh/
  #    - assets/assets_six/html/en/
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
